<a href="https://colab.research.google.com/github/Kashaf22/EREA_Research/blob/main/LearningPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [4,5]]
x_data = np.array(data);
print(x_data);
tensor_data = torch.from_numpy(x_data);
print(tensor_data)
tensor_data1 = torch.tensor(data);
print(tensor_data1);

[[1 2]
 [4 5]]
tensor([[1, 2],
        [4, 5]])
tensor([[1, 2],
        [4, 5]])


Check how Tensor inherits the properties of the arguments.Notice in the argument you can only pass a tensor not a regular list or ndarray

In [3]:
ones_data = torch.ones_like(tensor_data)
print(ones_data)
ones_data = torch.ones_like(tensor_data, dtype=torch.float)
print(ones_data)

tensor([[1, 1],
        [1, 1]])
tensor([[1., 1.],
        [1., 1.]])


Check how you can use shape to implemenet tensors


In [4]:
shape = (2,3)
data = torch.rand(shape)
print(data)

tensor([[0.9452, 0.6639, 0.6600],
        [0.4173, 0.7995, 0.5452]])


How to move Tensor to a GPU from a CPU. Remember GPU helps in better performance

In [5]:
print(f"Tensor is running on: \n {data.device} \n")
if torch.cuda.is_available():
  data = data.to('cuda')
  print(f"Now Tensor is on: \n {data.device} \n")

Tensor is running on: 
 cpu 



Baisc Operations on Tensors


In [6]:
tensor = torch.ones(3,3)
tensor[:,1] = -5
print(tensor)

tensor([[ 1., -5.,  1.],
        [ 1., -5.,  1.],
        [ 1., -5.,  1.]])


How to concatenate the tensors together

In [7]:
data2 = ([1,2,3], [1,2,6])
tensor_concat = torch.tensor(data2)
concat = torch.cat([tensor_concat, tensor_concat, tensor_concat], dim=0)
print(concat)

tensor([[1, 2, 3],
        [1, 2, 6],
        [1, 2, 3],
        [1, 2, 6],
        [1, 2, 3],
        [1, 2, 6]])


How to calculate the simple multiplication of two tensors. Each corresponding element is multiplied by itself

In [10]:
tensorM = tensor_concat.mul(tensor_concat);
print(tensorM)

tensor([[ 1,  4,  9],
        [ 1,  4, 36]])


How to add the inplace addition to tensors

In [15]:
tensorIP = concat.add_(2);
print(tensorIP);

tensor([[3, 4, 5],
        [3, 4, 8],
        [3, 4, 5],
        [3, 4, 8],
        [3, 4, 5],
        [3, 4, 8]])


Tensor to Numpy
** If Tensor and Numpy exist on the same CPU, they can share some memory locations so chaning tensor can affect numpy as well

In [16]:
x = torch.ones(4);
print(x);
y = x.numpy()
print(y);

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]


In [17]:
x = x.add_(3);
print(x);
print(y);

tensor([4., 4., 4., 4.])
[4. 4. 4. 4.]


Numpy to Tensor

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)
